version: '3.8'

services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server 

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=8080
    ports:
      - "8080:8080" 
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env
